### ISSUE TITLE
Error at Azure container instance: panic: open /root/.disbalancer-go-client/app: text file busy

### ISSUE THREAD

**Issue by UnitybaseExplorer** [disbalancer-project/main#14]
```
2022/04/01 06:23:13 updating...
started disbalancer-go-client
2022-04-01T06:23:14Z	Failed to read file:open proxies.txt: no such file or directory
2022-04-01T06:23:14Z	Failed to get country:open GeoLite2-Country.mmdb: no such file or directory
2022-04-01T06:23:14Z	Ready for attack...
2022-04-01T06:23:14Z	Searching for the Kremlin's target to defeat...
2022-04-01T06:23:17Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:20Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:23Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:26Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:29Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:32Z	Massive https://gosuslugi.ru/ attacking...
2022-04-01T06:23:35Z	Massive https://gosuslugi.ru/ attacking...
2022/04/01 06:23:38 updating...
panic: open /root/.disbalancer-go-client/app: text file busy

goroutine 39 [running]:
main.Unexpected(...)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:117
main.MustWrite(0xc00001a100, 0x20, 0xc000558000, 0x7be556, 0x8ac000)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:104 +0x125
main.main.func1(0x0)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:61 +0x1cc
main.main.func2()
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:67 +0x45
main.main.func3(0xc000010c30, 0xc00009a840, 0xc000010c20)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:80 +0x2b
created by main.main
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:79 +0x51a
```

**Comment by trinitiwowka** [comment]
Такая же проблема в докере, падает спустя какое-то время.

`2022/03/31 17:42:22 updating...

panic: open /root/.disbalancer-go-client/app: text file busy


goroutine 55 [running]:

main.Unexpected(...)

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:117

main.MustWrite(0xc00012a080, 0x20, 0xc0005f8000, 0x7be556, 0x8ac000)

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:104 +0x125

main.main.func1(0x12a05f200)

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:61 +0x1cc

main.main.func2()

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:67 +0x45

main.main.func3(0xc000010c30, 0xc0001dcdc0, 0xc000010c20)

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:80 +0x2b

created by main.main

/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:79 +0x51a`

**Comment by Gorlanson** [comment]
It was fixed in the latest version - v0.0.8
Please try it again
