### ISSUE TITLE
docker crashes sometime

### ISSUE THREAD

**Issue by bundzmm** [disbalancer-project/main#2]
Hi. I started docker version of your app on Linux (ARM64) but sometimes I see:

>  panic: open /root/.disbalancer-go-client/app: text file busy
> 
> goroutine 12 [running]:
> main.Unexpected(...)
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:117
> main.MustWrite(0x40000ea080, 0x20, 0x4000698000, 0x78195c, 0x8ac000)
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:104 +0x104
> main.main.func1(0x12a05f200)
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:61 +0x14c
> main.main.func2()
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:67 +0x48
> main.main.func3(0x400008ec10, 0x4000078000, 0x400008ec00)
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:80 +0x28
> created by main.main
>         /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:79 +0x3e4

And I should restart container again.

**Comment by ahalan** [comment]
Same:

```
│                                                                                                                                                                                                                    │
│   Massive https://ukraina.ru/ attacking...                                                                                                                                                                         │
│   Massive https://ukraina.ru/ attacking...                                                                                                                                                                         │
│   Massive https://ukraina.ru/ attacking...                                                                                                                                                                         │
│   Massive https://ukraina.ru/ attacking...                                                                                                                                                                         │
│   2022/03/17 19:05:42 updating...                                                                                                                                                                                  │
│   panic: open /root/.disbalancer-go-client/app: text file busy                                                                                                                                                     │
│   2022-03-17T19:05:42.831481055Z                                                                                                                                                                                   │
│   goroutine 16 [running]:                                                                                                                                                                                          │
│   main.Unexpected(...)                                                                                                                                                                                             │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:117                                                                                                                                      │
│   main.MustWrite(0xc0000aa080, 0x20, 0xc0009ca000, 0x7bc315, 0x8ac000)                                                                                                                                             │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:104 +0x125                                                                                                                               │
│   main.main.func1(0x12a05f200)                                                                                                                                                                                     │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:61 +0x1cc                                                                                                                                │
│   main.main.func2()                                                                                                                                                                                                │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:67 +0x45                                                                                                                                 │
│   main.main.func3(0xc000010c40, 0xc000096160, 0xc000010c30)                                                                                                                                                        │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:80 +0x2b                                                                                                                                 │
│   created by main.main                                                                                                                                                                                             │
│   /Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:79 +0x51a
```

**Comment by Gorlanson** [comment]
It was a problem in build, try with the latest version:

1) docker pull disbalancer/liberator:manifest-latest
2) docker run disbalancer/liberator:manifest-latest
