### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by rjb752** [disbalancer-project/main#8]
Sometimes the linux app (64bit v0.0.6), especially when run for a while and the VPN connection gets slow, the application might crash like this:
```
Massive hxxps://koronapay.com/ attacking...
Massive hxxps://koronapay.com/ attacking...
Massive hxxps://koronapay.com/ attacking...
Establishing a connection to the cyber army...
Massive hxxps://koronapay.com/ attacking...
Massive hxxps://koronapay.com/ attacking...
Massive hxxps://koronapay.com/ attacking...
Massive hxxps://koronapay.com/ attacking...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x687c76]

goroutine 1 [running]:
disbalancer-go-client/api.(*Api).Heartbeat(0x0, {0xc00001a780, 0x2f}, 0xc00000e060)
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/api/api.go:185 +0x96
main.main()
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/main.go:156 +0x7cb
restarting...
started disbalancer-go-client
```

After this the application went into a loop restarting itself over and over for about 50 times until it stopped with this:
```
Failed to read file:open proxies.txt: no such file or directory
Ready for attack...
Searching for the Kremlin's target to defeat...
Failed to get country:open GeoLite2-Country.mmdb: no such file or directory
2022/03/16 16:07:58 updating...
panic: open /home/lrlm/.disbalancer-go-client/app: text file busy

goroutine 41404 [running]:
main.Unexpected(...)
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:121
main.MustWrite({0xc0000b01e0, 0xc000604f10}, {0xc000204300, 0x5c2, 0x700})
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:108 +0xdc
main.main.func1()
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:61 +0x157
main.main.func2()
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:67 +0x38
main.main.func3()
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:80 +0x33
created by main.main
	D:/Work/disbalancer-go-resolver/disbalancer-go-client/launcher/main.go:79 +0x3f4
```

**Comment by rjb752** [comment]
this seems to be solved now with v0.0.7
